---
title: "p8105_hw5_yq2279"
author: "Qi Yuchen"
date: "2019/11/3"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

### The function for replacing missing values

```{r}
fill_na = function(x){
  if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))
  }
  else if (is.character(x)) {
    x = replace_na(x, "virginica")
  }
  else {
  stop("Not a valid input")
  }
  
  x
}
```

### Apply the function to the columns of iris_with_missing

```{r}
iris_na_filled = map_df(iris_with_missing, fill_na)
```

# Problem 2